<a href="https://colab.research.google.com/github/yuryychayka09-byte/Data_Analytics-/blob/main/LAB_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

It's a Practical work number two, amd this is start her

In [4]:
albums = {
    'band': [
        'Skillet', 'AC/DC', 'Linkin Park', 'KISS',
        'And One', 'Nirvana', 'Sepultura', 'Metallica'
    ],
    'album': [
        'Awake', 'Back in Black', 'Hybrid Theory', 'Destroyer',
        'Virgin Superstar', 'Nevermind', 'Roots', 'Master of Puppets'
    ],
    'year': [
        2009, 1980, 2000, 1976,
        2000, 1991, 1996, 1986
    ],
    'rating': [
        8.5, 9.6, 9.4, 8.7,
        7.9, 9.5, 8.8, 9.7
    ]
}

df_albums = pd.DataFrame(albums)
df_albums

          band              album  year  rating
0      Skillet              Awake  2009     8.5
1        AC/DC      Back in Black  1980     9.6
2  Linkin Park      Hybrid Theory  2000     9.4
3         KISS          Destroyer  1976     8.7
4      And One   Virgin Superstar  2000     7.9
5      Nirvana          Nevermind  1991     9.5
6    Sepultura              Roots  1996     8.8
7    Metallica  Master of Puppets  1986     9.7

it's were first step

In [7]:
from google.colab import drive
drive.mount('/content/drive')

df_sales = pd.read_csv('/content/drive/MyDrive/Coffe_sales.csv')

df_sales.head()

Mounted at /content/drive

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time
0,10,card,38.7,Latte,Morning,Fri,Mar,5,3,2024-03-01,10:15:50.520000
1,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:19:22.539000
2,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:20:18.089000
3,13,card,28.9,Americano,Afternoon,Fri,Mar,5,3,2024-03-01,13:46:33.006000
4,13,card,38.7,Latte,Afternoon,Fri,Mar,5,3,2024-03-01,13:48:14.626000

In [8]:
df_sales.info()
df_sales.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3547 entries, 0 to 3546
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   hour_of_day  3547 non-null   int64
 1   cash_type    3547 non-null   object
 2   money        3547 non-null   float64
 3   coffee_name  3547 non-null   object
 4   Time_of_Day  3547 non-null   object
 5   Weekday      3547 non-null   object
 6   Month_name   3547 non-null   object
 7   Weekdaysort  3547 non-null   int64
 8   Monthsort    3547 non-null   int64
 9   Date         3547 non-null   object
 10  Time         3547 non-null   object
dtypes: float64(1), int64(3), object(7)
memory usage: 304.9+ KB

       hour_of_day        money  Weekdaysort    Monthsort
count  3547.000000  3547.000000  3547.000000  3547.000000
mean     14.185791    31.645216     3.845785     6.453905
std       4.234010     4.877754     1.971501     3.500754
min       6.000000    18.120000     1.000000     1.000000
25%      10.000000    27.920000     2.000000     3.000000
50%      14.000000    32.820000     4.000000     7.000000
75%      18.000000    35.760000     6.000000    10.000000
max      22.000000    38.700000     7.000000    12.000000

In [9]:
row_iloc = df_sales.iloc[2]
row_loc = df_sales.loc[2]
value = df_sales.loc[5, 'money']

In [10]:
mask_high = df_sales['money'] > 35
high_sales = df_sales[mask_high]
high_sales.head()

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time
0,10,card,38.7,Latte,Morning,Fri,Mar,5,3,2024-03-01,10:15:50.520000
1,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:19:22.539000
2,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:20:18.089000
4,13,card,38.7,Latte,Afternoon,Fri,Mar,5,3,2024-03-01,13:48:14.626000
6,16,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,16:19:02.756000

In [11]:
sorted_sales = df_sales.sort_values('money', ascending=False)
sorted_sales.head()

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time
131,10,card,38.7,Latte,Morning,Sat,Mar,6,3,2024-03-23,10:43:59.559000
133,13,card,38.7,Cappuccino,Afternoon,Sat,Mar,6,3,2024-03-23,13:10:07.661000
134,13,card,38.7,Cocoa,Afternoon,Sat,Mar,6,3,2024-03-23,13:11:12.230000
236,12,card,38.7,Cappuccino,Afternoon,Sun,Apr,7,4,2024-04-14,12:24:39.028000
235,17,card,38.7,Cappuccino,Night,Sat,Apr,6,4,2024-04-13,17:53:19.237000

In [12]:
final = df_sales[df_sales['money'] > 35].sort_values('money', ascending=False)
final.to_csv('/content/drive/MyDrive/filtered_sales.csv', index=False)
print("Файл збережено!")

Файл збережено!

In this work the file Coffe_sales.csv was imported into Google Colab. The table was checked with info() and describe() to see the structure and numbers. Indexing was done with iloc and loc to show the difference between position and label. Filtering was used to keep only rows where money > 35. Sorting was done by the column money in descending order to find the biggest transactions. At the end the results were saved into a new CSV file.

This shows the basic skills of Pandas: import, view, indexing, filtering, sorting, and saving data. These steps are the base for more complex analysis later.